### PR TITLE
Fix to print error message

### LINKED ISSUE #79: Add error message when target directory of `--sprite-input `and/or `--sprite-output` is not exist.
**Describe the bug**

When I run `charites build style.yml style.json --sprite-input noExistDir --sprite-output noExistDir`, I don't get any error message even if the directory specified in the `--sprite-input` and/or `--sprite-output` is missing.

**To Reproduce**

In the example below, `noExistDir` is a directory that does not exist.

```
charites build style.yml style.json --sprite-input icons --sprite-output noExistDir
```

```
charites build style.yml style.json --sprite-input icons --sprite-output noExistDir
```

**Expected behavior**

It should show error message.

**Screenshots**

**Charites Version:**

- Charites version: 0.1.3 (It is on `main` branch)

**Desktop (please complete the following information):**

- OS: Mac

### PR DESCRIPTION
**Pull request by naogify**
@keichan34 @kamataryo @JinIgarashi. I fixed the bug, could you review this PR?
cc @ubukawa @hfu 

## Description

Fix to print error message. 

When we run `charites build style.yml style.json --sprite-url http://localhost:8080`, Charites should return `Invalid sprite url format.`. But, it hasn't return any error message. So, I fixed it.

## Type of Pull Request

- [ ] Adding a feature
- [x] Fixing a bug
- [ ] Maintaining documents
- [ ] Others ()

## Verify the followings

- [x] Code is up-to-date with the `main` branch
- [x] No build errors after `npm run build`
- [x] No lint errors after `npm run lint`
- [x] No errors on using `charites help` globally
- [x] Make sure all the exsiting features working well
- [ ] Have you added at least one unit test if you are going to add new feature?
- [ ] Have you updated documentation?

Refer to [CONTRIBUTING.MD](https://github.com/unvt/charites/tree/master/.github/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Review by JinIgarashi — APPROVED** [review]
Thank you. Looks fine

File: src/lib/error.ts [hunk 1]
```diff
@@ -1,6 +1,8 @@
 export const error = (e: unknown) => {
   if (e instanceof TypeError) {
     console.error(e.message)
+  } else if (typeof e === 'string') {
```
Comment (keichan34) [inline src/lib/error.ts]: I think that instead of checking if the error is a string here, we should just do something like

```
} else {
  console.error(e.toString())
}
```

That way, it will catch other errors as well. Does anyone know if there was a reason for suppressing error outputs and limiting it to only TypeError?

**Review by keichan34 — APPROVED** [review]

**Comment by naogify** [comment]
@keichan34 @JinIgarashi 
Thank you! I'll merge it now.
